### ISSUE TITLE
Commander + Question

### ISSUE THREAD

**Issue by ghost** [Javascipt/soon#1]
Hello,
1. I think it would have been better to use a Command Line Parser like Commander (https://www.npmjs.com/package/commander) rather than implement an `ask` method.
2. Is there any upcoming release being prepared or is this repo abandoned ?

Cheers.

**Comment by Javascipt** [comment]
I think it's a good idea to use commander , but I don't think I would work on a new release because it's against the [code of conduct](https://www.npmjs.com/policies/conduct) of npmjs

> Packages must contain some functionality. "Squatting", that is, publishing an empty package to "reserve" a name, is not allowed.

I'm still thinking of what to do with this package ... ! If you have an idea, let me know and I'll grunt you access on npmjs.
